version: '3'
services:
  MySql:
    image: MySql
    container_name: MySql
    restart: always
    environment:
      ## Note: all of these environment variables can also be loaded from .env

      MySql_DATABASE: '${TEST_DB_DATABASE}'
      # So you don't have to use root, but you can if you like
      MySql_USER: '${TEST_DB_USERNAME}'
      # You can use whatever password you like
      MySql_PASSWORD: '${TEST_DB_PASSWORD}'
      # Password for root access
      MySql_ROOT_PASSWORD: '${TEST_DB_ROOT_PASSWORD}'
      # Good for testing, but not production
      MySql_ALLOW_EMPTY_PASSWORD: '${TEST_DB_ALLOW_EMPTY_PASSWORD}'

    ports:
      # <Port exposed> : < MySql Port running inside container>
      # default is:
      #- '3306:3306'
      - '${TEST_DB_PORT}:${TEST_DB_PORT}'
    expose:
      # Opens port 3306 on the container
      # default is:
      #- '3306'
      - '${TEST_DB_PORT}'
      # Where our data will be persisted
    volumes:
      - MySql:/data/MySql
    env_file:
      - .env

volumes:
  MySql:
    driver: local
